#!/bin/bash
# Modified by kunphiphit
red='\e[1;31m'
green='\e[0;32m'
NC='\e[0m'
echo "Connecting to Server..."
sleep 0.4
echo "Checking Permision..."
sleep 0.3
CEK=kunphiphit
if [ "$CEK" != "kunphiphit" ]; then
		echo -e "${red}Permission Denied!${NC}";
        echo $CEK;
        exit 0;
else
echo -e "${green}Permission Accepted...${NC}"
sleep 1
clear
fi

IP=$(wget -qO- ipv4.icanhazip.com)
read -p "How many accounts will be created?: " banyakuser
read -p "How many days?                    : " aktif
today="$(date +"%Y-%m-%d")"
expire=$(date -d "$aktif days" +"%Y-%m-%d")
clear
echo " "
echo " "
echo " "
echo "-----------------------------------"
echo "        Account Information        "
echo "-----------------------------------"
echo "   Host/IP        : $IP"
echo "   OpenSSH        : 22, 143"
echo "   Dropbear       : 442, 110, 109"
echo "   Squid Proxy    : 8000, 8080, 8081, 8082, 8989, 3128"
echo "   OpenVPN Config : http://$IP/client.ovpn"
echo "   Until On       : $(date -d "$aktif days" +"%d-%m-%Y")"
  echo "----------------------------------"
for (( i=1; i <= $banyakuser; i++ ))
do
	USER=`cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 15 | head -n 1`
	useradd -M -N -s /bin/false -e $expire $USER
	PASS=`cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 15 | head -n 1`;
	echo $USER:$USER | chpasswd
	echo "$i. Username/Password: $USER"
done

  echo "--------------------------------------"
  echo " "